<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2025-present OpenRefactory, Inc.
  ~
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.openrefactory</groupId>
  <artifactId>parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>parent</name>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <tycho-version>5.1.0</tycho-version>
  </properties>

  <modules>
    <module>bundles</module>
    <module>features</module>
    <module>products</module>
  </modules>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>target-platform-configuration</artifactId>
          <version>${tycho-version}</version>
        </plugin>

        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-maven-plugin</artifactId>
          <version>${tycho-version}</version>
        </plugin>

        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-p2-director-plugin</artifactId>
          <version>${tycho-version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>

      <!--
        ~ Tycho extension for building Eclipse plugins, RCP applications, and OSGi bundles with Maven.
        -->
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <extensions>true</extensions>
      </plugin>

      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <configuration>
          <!-- Location of the target platform relative to the submodules -->
          <target>
            <file>${maven.multiModuleProjectDirectory}/target-platform.target</file>
          </target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.43.0</version>
        <configuration>
          <java>
            <includes>
              <include>src-api/**/*.java</include>
              <include>src-internal-api/**/*.java</include>
              <include>src-internal/**/*.java</include>
            </includes>
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
