source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/antlr-4.9.1-complete.jar
jars.extra.classpath = lib/antlr-4.9.1-complete.jar
